title: "Eugen Barilyuk EB43 GitHub Portfolio"
description: "Personal site hosted on GitHub Pages"

url: "https://eb43.github.io"
plugins:
  - jekyll-sitemap

# ensure Jekyll will process our custom sitemap.xml
include:
  - sitemap.xml